namespace: default

createNamespaces: true

# Part 1: the configuration of mongodb and mysql
# We use external charts from bitnami, and pass the values stated below to them.
# For bitnami/mysql, check out: https://artifacthub.io/packages/helm/bitnami/mysql
# For bitnami/mongodb, check out: https://artifacthub.io/packages/helm/bitnami/mongodb
#
#mysqlPv:
#  name: mysql-pv
#  size: 10Gi
#  path: /mnt/data/mysql # the path on the node that contains the pv
#  node: minikube # the node that contains the pv

mysql:
  image:
    debug: true

  initdbScriptsConfigMap: mysql-init-script

  auth:
    createDatabase: true
    rootPassword: texera
    database: texera_db
    username: texera
    password: texera

#  primary:
#    startupProbe:
#      initialDelaySeconds: 60
#
#    persistence:
#      enabled: true
#      existingClaim: mysql-pvc
#
#  architecture: standalone

# Part 2: Configuration of Texera
workflowComputingUnitManager:
  name: workflow-computing-unit-manager
  numOfPods: 1
  serviceAccountName: workflow-computing-unit-manager-service-account
  imageName: kelvinyz/texera-pod-brain:test-env
  service:
    type: NodePort # for testing purpose, NodePort mode is fine
    port: 8888 # port of the pod
    nodePort: 30082 # exposed port

# Configuration for the workflow pod
# TODO: consider remove this
workflowComputingUnit:
  name: workflow-computing-unit
  numOfPods: 1
  imageName: pureblank/backend-image:implement-power-button # image name of the workflow pod

webserver:
  name: webserver
  numOfPods: 1  # Number of pods for the Texera deployment
  imageName: kelvinyz/texera-full-stack:ingress-test # image name of the texera
  pv: # pv is used to store the user-resources, i.e. /core/amber/user-resources
    nodeAffinityNode: minikube # Node where the PV is mounted
    name: texera-pv
    size: 20Gi
    path: /mnt/data/texera
    accessModes:
      - ReadWriteMany  # This enables multiple read/write access
  service:
    type: NodePort # for testing purpose, NodePort mode is fine
    port: 8080 # port of the pod
    nodePort: 30081 # exposed port

# Config required for envoy and workflow pods
envoy:
  replicas: 1
  image:
    repository: envoyproxy/envoy
    tag: v1.31-latest
  port:
    10000
  debug: false
  service:
    type: NodePort
    port: 10000
    nodePort: 30083

workflowComputingUnits:
  name: workflow-computing-units
  namespace: wf-pod-pool
  service:
    port: 8080
    targetPort: 8080


# Ingress dependency configs
ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: NodePort
      nodePorts:
        http: 30080
    ingressClassResource:
      name: nginx
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  rbac:
    create: true


# Custom Ingress resource configs
ingress:
  enabled: true
  hostname: "texera.example.com"
  paths:
    - path: /
      serviceName: webserver-svc
      servicePort: 8080
    - path: /api
      serviceName: webserver-svc
      servicePort: 8080
    - path: /rtc
      serviceName: webserver-svc
      servicePort: 1234
    - path: /workflowpod
      serviceName: texera-wf-brain-svc
      servicePort: 8888
    - path: /wsapi/workflow-websocket
      serviceName: envoy-svc
      servicePort: 10000
