apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservices.chatAssistantService.name }}-svc   # ⇒ chat-assistant-service-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.microservices.chatAssistantService.service.type }}  # ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Values.microservices.chatAssistantService.name }}
  ports:
      - protocol: TCP
        port: {{ .Values.microservices.chatAssistantService.service.port }}      # 9095
        targetPort: {{ .Values.microservices.chatAssistantService.service.port }}