apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webserver.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.webserver.service.type }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.webserver.name }}
  ports:
    - name: api-port
      protocol: TCP
      port: {{ .Values.webserver.service.port }}
      targetPort: {{ .Values.webserver.service.port }}
      # if service type is set to NodePort, include nodePort attribute
      {{- if eq .Values.webserver.service.type "NodePort" }}
      nodePort: {{ .Values.webserver.service.nodePort }}
      {{- end }}

    # --- RTC does not work ---
    # TODO: run this as a separate deployment and service
    - name: rtc-port
      protocol: TCP
      port: 1234
      targetPort: 1234
      {{- if eq .Values.webserver.service.type "NodePort" }}
      nodePort: 30084
      {{- end }}