apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workflowComputingUnitManager.serviceAccountName }}
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.workflowComputingUnitManager.name }}
  namespace: {{ .Values.workflowComputingUnits.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.workflowComputingUnitManager.name }}-binding
  namespace: {{ .Values.workflowComputingUnits.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.workflowComputingUnitManager.serviceAccountName }}
    namespace: default
roleRef:
  kind: Role
  name: {{ .Values.workflowComputingUnitManager.name }}
  apiGroup: rbac.authorization.k8s.io