apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workflowPodBrain.name }}
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-pod-manager
  namespace: {{ .Values.workflowPods.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-pod-brain-binding
  namespace: {{ .Values.workflowPods.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.workflowPodBrain.name }}
    namespace: default
roleRef:
  kind: Role
  name: workflow-pod-manager
  apiGroup: rbac.authorization.k8s.io